version: '3'
services:
  faust-example:
    tty: true
    build: ./faust-project/example
    command: ./run.sh
    depends_on:
      - zookeeper
      - kafka
    environment:
      - WORKER=example
      - WORKER_PORT=6066
      - KAFKA_BOOTSTRAP_SERVER=kafka://kafka:9092
      - KAFKA_BOOSTRAP_SERVER_NAME=kafka
      - KAFKA_BOOSTRAP_SERVER_PORT=9092
      - PYTHONPATH=:/faust-project

    ports:
      - "8084:80"
      - "8000:8000"
    volumes:
      - ./faust-project/example:/faust-project/example
  faust-streaming:
    tty: true
    build: ./faust-project/faust_streaming
    command: ./run.sh
    depends_on:
      - zookeeper
      - kafka
    environment:
      - WORKER=faust_streaming
      - WORKER_PORT=6066
      - KAFKA_BOOTSTRAP_SERVER=kafka://kafka:9092
      - KAFKA_BOOSTRAP_SERVER_NAME=kafka
      - KAFKA_BOOSTRAP_SERVER_PORT=9092
      - PYTHONPATH=:/faust-project

    ports:
      - "8085:80"
      - "8001:8000"
    volumes:
      - ./faust-project/faust_streaming:/faust-project/faust_streaming
  django_faust_streaming:
    tty: true
    build: ./faust-project/mysite
    command: ./run.sh
    depends_on:
      - zookeeper
      - kafka
    environment:
      - WORKER=django_faust_streaming
      - WORKER_PORT=6066
      - KAFKA_BOOTSTRAP_SERVER=kafka://kafka:9092
      - KAFKA_BOOSTRAP_SERVER_NAME=kafka
      - KAFKA_BOOSTRAP_SERVER_PORT=9092
      - DJANGO_SETTINGS_MODULE=mysite.mysite.settings
      - PYTHONPATH=:/faust-project

    ports:
      - "8086:80"
      - "8006:8000"
    volumes:
      - ./faust-project/mysite:/faust-project/mysite
  zookeeper:
    image: "confluentinc/cp-zookeeper"
    hostname: zookeeper
    ports:
      - 32181:32181
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
    - 9092:9092
    - 29092:29092
    depends_on:
    - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:29092,PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1

